spring:
  security:
    oauth2:
      authorizationserver:
        client:
          crm-client:
            require-authorization-consent: true
            registration:
              # crm/crm
              client-id: crm
              client-secret: "{bcrypt}$2a$10$P2gRo9oiz/8rt2cq7KPJ7ergyWoYLj6jOrsxqv0cCY96YvgHhRCzK"
              authorization-grant-types: client_credentials, authorization_code, refresh_token
              redirect-uris: http://127.0.0.1:8200/login/oauth2/code/spring
              scopes: user.read, user.write, openid
              client-authentication-methods: client_secret_basic
server:
  port: 9000
issuer-uri: http://localhost:8200

