spring:
  security:
    oauth2:
      authorizationserver:
        client:
          crm-client:
            require-authorization-consent: true
            registration:
              # crm/crm
              client-id: crm
              client-secret: "{bcrypt}$2a$10$UCELFQmGzK3HokxFlxHcd.sWBMBk7Dq2K0fXj3LCQuH8nqw7XbREu"
              authorization-grant-types: client_credentials, authorization_code, refresh_token
              redirect-uris: http://127.0.0.1:8082/login/oauth2/code/spring
              scopes: user.read, user.write, openid
              client-authentication-methods: client_secret_basic

